import './login/login.component'
import './welcome/welcome.component'
import './stamps/list.component'
import './stamps/create.component'
import './stamps/add.component'
import './stamps/collection-detail.component'
import './stamps/stamp-detail.component'
